/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs2263hw04;

import com.google.common.graph.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

public class App {

    /*
    Generates a graph, gives it to the manager (which accepts a visitor), which is visited by
    a visitor which prints the relationships between individuals, and a visitor which prints a
    count of relationships.

     */

    private static void run(){
        Network SocialNetwork = new NetworkGraphGenerator().generateGraph();
        NetworkGraphManager Manager = new NetworkGraphManager(SocialNetwork);

        String relationships = new GraphRelationshipToStringVisitor().visitGraph(Manager);
        String relationshipCount = new RelationshipSummarizerVisitor().visitGraph(Manager);

        System.out.println(relationships);
        System.out.println(relationshipCount);


    }

    public static void main(String args[]){
        run();
    }

}
